# Generated by Django 6.0.6 on 2026-07-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mead',
            name='gallons',
            field=models.IntegerField(choices=[(1, '1 Gallon'), (3, '3 Gallons'), (5, '5 Gallons')], default=1),
        ),
    ]
