# Generated by Django 6.0.6 on 2026-07-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_mead_gallons'),
    ]

    operations = [
        migrations.AddField(
            model_name='mead',
            name='name',
            field=models.CharField(default='Mead', max_length=50),
        ),
    ]
