# Generated by Django 6.0.6 on 2026-07-26 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_mead_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mead',
            old_name='ingredients',
            new_name='recipe',
        ),
    ]
