# Generated by Django 6.0.6 on 2026-07-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_ingredients_mead_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mead',
            old_name='recipe',
            new_name='ingredients',
        ),
    ]
