# Generated by Django 6.0.6 on 2026-07-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_recipe_mead_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='mead',
            name='equipment',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='mead',
            name='instructions',
            field=models.JSONField(default=list),
        ),
    ]
