# Generated by Django 6.0.6 on 2026-08-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_mead_equipment_mead_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mead',
            name='equipment',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='mead',
            name='ingredients',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='mead',
            name='instructions',
            field=models.JSONField(default=dict),
        ),
    ]
