# Generated by Django 6.0.6 on 2026-08-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_mead_equipment_alter_mead_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mead',
            name='final_gravity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mead',
            name='original_gravity',
            field=models.FloatField(default=0),
        ),
    ]
