# Generated by Django 6.0.6 on 2026-08-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_mead_final_gravity_mead_original_gravity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mead',
            name='fermentation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
