# Generated by Django 6.0.6 on 2026-08-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_mead_fermentation_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mead',
            name='alcohol_by_volume',
            field=models.FloatField(default=0),
        ),
    ]
